workflows:
  my-workflow:
    instance_type: mac_mini_m1
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
    scripts:
      - name: Build for Android
        script: flutter build apk
    publishing:
      email:
        recipients:
          - tauqeereusopht@gmail.com
        notify:
          success: true
          failure: false
